language: go

go:
    - 1.8.x
    - tip

install:
    - curl -fsSL -o ./dep https://github.com/golang/dep/releases/download/v0.3.2/dep-linux-amd64 && chmod +x ./dep

before_script:
    - ./dep ensure

script:
    - go test -short -race $(go list ./... | grep -v /vendor/)
