language: go

go:
    - 1.8.x
    - tip

install:
    - curl -fsSL -o $GOPATH/bin/dep https://github.com/golang/dep/releases/download/v0.3.2/dep-linux-amd64 && chmod +x $GOPATH/bin/dep

script:

    - |
        [ "${TRAVIS_EVENT_TYPE}" == "cron" ] || \
        (make vendor && make build && make test)

    - |
        [ "${TRAVIS_EVENT_TYPE}" != "cron" ] || \
        ( \
            docker build -t setekhid/ketos:latest . && \
            cd test && bash ./test.sh \
        )
